// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjILqezFk1ZuQTvyNJp5c4wwxh69OBKA',
    appId: '1:1020836718322:web:f525d7acdde4320dfb526b',
    messagingSenderId: '1020836718322',
    projectId: 'chatttapp-ab52f',
    authDomain: 'chatttapp-ab52f.firebaseapp.com',
    storageBucket: 'chatttapp-ab52f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09OMzRccX516fDue4q-UBFYb0CBKTD7Y',
    appId: '1:1020836718322:android:a43f7d3f9c3d1df9fb526b',
    messagingSenderId: '1020836718322',
    projectId: 'chatttapp-ab52f',
    storageBucket: 'chatttapp-ab52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlaANpkp5F1_NfmMySLgbfpn9MJAX7KkA',
    appId: '1:1020836718322:ios:1468c34b25cc6f3dfb526b',
    messagingSenderId: '1020836718322',
    projectId: 'chatttapp-ab52f',
    storageBucket: 'chatttapp-ab52f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlaANpkp5F1_NfmMySLgbfpn9MJAX7KkA',
    appId: '1:1020836718322:ios:1468c34b25cc6f3dfb526b',
    messagingSenderId: '1020836718322',
    projectId: 'chatttapp-ab52f',
    storageBucket: 'chatttapp-ab52f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwjILqezFk1ZuQTvyNJp5c4wwxh69OBKA',
    appId: '1:1020836718322:web:e1e10c04ef1e9f6ffb526b',
    messagingSenderId: '1020836718322',
    projectId: 'chatttapp-ab52f',
    authDomain: 'chatttapp-ab52f.firebaseapp.com',
    storageBucket: 'chatttapp-ab52f.firebasestorage.app',
  );
}
